package model.services.views;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 22 20:52:57 IST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AvailabilityVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        availability;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AvailabilityVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AvailabilityVORowImpl.AttributesEnum.firstIndex() + AvailabilityVORowImpl.AttributesEnum
                                                                                            .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AvailabilityVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int AVAILABILITY = AttributesEnum.availability.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AvailabilityVORowImpl() {
    }
}

