package model.services.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 21 10:48:20 IST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrderStatusListVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OrderStatusListVOImpl() {
    }
}

