package model.services.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 26 10:30:46 IST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PaymentMethod_forCustApp_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PaymentMethod_forCustApp_VOImpl() {
    }
}

