package model.services.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 22 14:43:36 IST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RevenueImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RevenueImpl() {
    }
}

